services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rendezvous-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - rendezvous-network

  nginx:
    image: nginx:alpine
    container_name: rendezvous-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rendezvous-network
    depends_on:
      - app

networks:
  rendezvous-network:
    driver: bridge
